# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: ITA19-Pipeline
# Siia panna kuna Workflow peaks jookma
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


# Erinevad tööd siia plokki
